services:
  auth:
    image: auth
    build:
      context: services
      dockerfile: auth.Dockerfile
    env_file:
      - ./services/apis/auth/.env
    environment:
      NODE_ENV: development
    ports:
      - 4000:4000
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "./apis/auth/server.js"]
