services:
  account-service:
    image: account-service
    build:
      context: services
      dockerfile: accountService.Dockerfile
    env_file:
      - ./services/apis/account-service/.env
    environment:
      NODE_ENV: production
    ports:
      - 4000:4000
